### ISSUE TITLE
Would be nice to filter on "Hearts"

### ISSUE THREAD

**Issue by VikingAntics** [CypherDoesStuff/CyberAssets#2]
Hi,

Very nice asset.  I like what you've done with the preview pane.

I think the "Hearts" would be much more useful if you could filter your lists based on the ones we marked?  I guess in the current implementation, you can see the ones you "Hearted" as you scroll through the lists, but that seems cumbersome.  

Thanks for sharing your asset with us.

**Comment by CypherDoesStuff** [comment]
Oh, have you seen the favorites tab? That tab should contain all of your favorited assets from the library.

![image](https://github.com/CypherDoesStuff/CyberAssets/assets/49430326/fcf44d48-02cf-4435-a3a3-3ec40c71f616)

**Comment by VikingAntics** [comment]
LOL.  I don't know how I missed that!!!  Maybe I need my eyeglasses upgraded. :-)

Thank you for pointing that out!!!

**Comment by CypherDoesStuff** [comment]
lol, no problem.
