### ISSUE TITLE
basic userguide?

### ISSUE THREAD

**Issue by ExileFox** [CypherDoesStuff/CyberAssets#3]
I don't see if after enabling it?

**Comment by CypherDoesStuff** [comment]
Hm, interesting. you should be able to check if its working since the AssetLib would be renamed to just "Assets". Was there any change after restarting Godot?

**Comment by ExileFox** [comment]
Oh. i completely overlooked that. It works, but there seems to always be file conflicts as the checkbox "ignore asset root" constantly resets which is unfortunate.
